[rgbd] # <tracker-name>
label = rgbd
protocol = traxpython
command = seatrack_baseline
# Specify a path to trax python wrapper if it is not visible (separate by ; if using multiple paths)
paths = /data/seatrack/lib/test/vot
